// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcrmxbpbpttqtfswyswn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjcm14YnBicHR0cXRmc3d5c3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjQyMDYsImV4cCI6MjA2NDAwMDIwNn0.i68bVYOC7BRdfEE5x57-gULJ5fLWZO3qad9qHZ_9DmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);